spring.application.name=canopy-backend

# Datasource Configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/canopy-db
spring.datasource.username=user
spring.datasource.password=password

# JPA & Flyway Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true